[mongodb]
mongodb-dev.dawsproject.online

[catalogue]
catalogue-dev.dawsproject.online

#user and password for all the hosts
#no need to specify for each host separately
[all:vars]
ansible_user=ec2-user
ansible_password=DevOps321
MONGODB_HOST=mongodb-dev.dawsproject.online