- name: create ec2 and route53 records
  hosts: all
  connection: local
  vars:
    sg_id: sg-035ed7cc952446c58
    ami_id: ami-0220d79f3f480ecf5
    environments: dev
    instances:
    - mongodb
    - catalogue
  tasks:
  - name: create ec2 instance
    amazon.aws.ec2-instance:
      instance_type: "t3.micro"
      security_group: "{{ sg_id }}"
      image_id: "{{ ami_id }}"
      name: "{{ item }}-{{ environments }}"  
      tags:
        Project: roboshop
        Component: "{{ item }}"
        Environment: "{{ environments }}"
        Name: "{{ item }}-{{ environments}}"
    loop: "{{ instances }}"  
    register: ec2_output

  - name: print the ec2_output
    ansible.builtin.debug:
      msg: "{{ ec2_output }}"