- name: create ec2 and route53 records
  hosts: all
  connection: local
  vars:
    sg_id: sg-035ed7cc952446c58
    ami_id: ami-0220d79f3f480ecf5
    domain_name: dawsproject.online
    environments: dev
    instances:
    - mongodb
    - catalogue
  tasks:
  - name: create ec2 instance
    amazon.aws.ec2_instance:
      instance_type: "t3.micro"
      security_group: "{{ sg_id }}"
      image_id: "{{ ami_id }}"
      name: "{{ item }}-{{ environments }}"  
      tags:
        Project: roboshop
        Component: "{{ item }}"
        Environment: "{{ environments }}"
        Name: "{{ item }}-{{ environments}}"
    loop: "{{ instances }}"  
    register: ec2_output

  - name: print the ec2_output
    ansible.builtin.debug:
      msg: "{{ ec2_output }}"

  - name: create route53 record
    amazon.aws.route53:
      state: present
      zone: "{{ domain_name }}"
      record: "{{ item.item }}-{{ environments }}.{{ domain_name }}"
      type: A
      ttl: 1
      value: "{{ item.instances[0].private_ip_address }}"
      wait: true
    loop: "{{ ec2_output.results }}"

  - name: create route53 record for frontend
    amazon.aws.route53:
      state: present
      zone: "{{ domain_name }}"
      record: "roboshop-{{ environments }}.{{ domain_name }}"
      type: A
      ttl: 1
      value: "{{ item.instances[0].public_ip_address }}"
      wait: true
    loop: "{{ ec2_output.results }}"
    when: item.item == 'frontend'